package com.zhongbai233.net_music_can_play_bili.client;

import java.util.UUID;

/** Helpers for Pad media session ids generated by PadPlaybackControlPacket. */
final class PadClientMediaSessionIds {
    private static final String MARKER = "-pad-";

    private PadClientMediaSessionIds() {
    }

    static boolean isPadSession(String sessionId) {
        return sessionId != null && sessionId.contains(MARKER);
    }

    static UUID pointId(String sessionId) {
        if (!isPadSession(sessionId)) {
            return null;
        }
        int start = sessionId.indexOf(MARKER) + MARKER.length();
        if (sessionId.length() < start + 36) {
            return null;
        }
        try {
            return UUID.fromString(sessionId.substring(start, start + 36));
        } catch (IllegalArgumentException ignored) {
            return null;
        }
    }
}